spring:
  application:
    name: back
  profiles:
    active: local

jwt:
  access-token-expiration: 900000        # 15분
  refresh-token-expiration: 1209600000   # 14일
  # 공통 설정 (profiles.active: local, jwt.expiration)